name: Step 0 # Start Course

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  COURSE_NAME: "Introduction to GitHub"

jobs:
  disable_workflows:
    name: Disable workflows
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable all workflows
        run: |
          workflows=$(git ls-files | grep -E '\.yml$|\.yaml$')
          for workflow in $workflows; do
            workflow_name=$(basename $workflow)
            gh workflow disable "$workflow_name"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  start_course:
    name: Start Course
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Deactivate 'Start Course' button
        run: |
          # Remove href from 'Start Course' button
          target='id="copy-course"[^>]*href="[^"]*"'
          replacement='id="copy-course"'
          sed -i "s|$target|$replacement|g" README.md

          # Change color from green to gray
          target=Copy_Course-008000
          replacement=Copy_Course-AAA
          sed -i "s|$target|$replacement|g" README.md

      - name: Activate 'Start Lesson' button
        run: |
          # Add link to issue
          target='id="start_lesson"'
          replacement='id="start_lesson" href="../../issues/1"'
          sed -i "s|$target|$replacement|g" README.md

          # Change color from gray to green
          target=Start_Lesson-AAA
          replacement=Start_Lesson-008000
          sed -i "s|$target|$replacement|g" README.md

      - name: Replace relative links in readme
        run: |
          target=../../
          replacement=https://github.com/${{ github.repository }}/
          sed -i "s|$target|$replacement|g" README.md

      - name: Push README changes
        run: |
          git add README.md
          git commit --message="Start course"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_next_step_content:
    name: Post next step content
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Build welcome message from template
        id: build-issue-description
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/welcome.md
          template-vars: |
            title=Introduction to GitHub
            login=${{ github.actor }}
            intro_message=If you are new to GitHub, you might find your fellow developers use ___**issues**___  to organize their work and collaborate. We will do the same! That's another lesson, but today, we will introduce you to the basics.

      - name: Create issue - add welcome message
        id: create-issue
        run: |
          issue_url=$(gh issue create \
            --title "Course: $COURSE_NAME" \
            --body "${{ steps.build-issue-description.outputs.updated-text }}")
          echo "ISSUE_URL=$issue_url" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file .github/steps/1-create-a-branch.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          # gh workflow enable "Step 0" # Already disabled
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
